;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-babel-insert-hyphen
	LaTeX-insert-left-brace
	TeX-insert-backslash
	TeX-insert-sub-or-superscript
	ace-jump-mode
	ace-jump-move
	comment-dwim
	dabbrev-expand
	delete-horizontal-space
	dired-maybe-insert-subdir
	dired-next-line
	dired-unmark-backward
	electric-newline-and-maybe-indent
	ess-indent-or-complete
	ess-smart-comma
	ess-yank
	forward-sexp
	indent-for-tab-command
	indent-region
	insert-register
	kill-region
	kill-sexp
	markdown-exdent-or-delete
	matlab-electric-comment
	matlab-forward-sexp
	org-beginning-of-line
	org-ctrl-c-ctrl-c
	org-cycle
	org-delete-char
	org-end-of-line
	org-kill-line
	org-open-line
	org-self-insert-command
	org-time-stamp-inactive
	org-yank
	reindent-then-newline-and-indent
	sgml-close-tag
	sgml-slash
	transpose-words
	))

(setq mc/cmds-to-run-once
      '(
	ace-jump-add-multiple-cursor
	ace-jump-move
	ajmc/add-char
	ajmc/add-multiple-cursors
	ajmc/add-single-cursor
	ajmc/keyboard-reset
	describe-key
	eval-expression
	find-file
	handle-switch-frame
	helm-M-x
	wdired-exit
	wdired-finish-edit
	))
