;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	TeX-insert-backslash
	delete-horizontal-space
	dired-next-line
	dired-unmark-backward
	electric-newline-and-maybe-indent
	ess-smart-comma
	forward-sexp
	indent-for-tab-command
	insert-register
	kill-region
	kill-sexp
	org-beginning-of-line
	org-cycle
	org-end-of-line
	org-open-line
	org-self-insert-command
	sgml-close-tag
	sgml-slash
	))

(setq mc/cmds-to-run-once
      '(
	find-file
	helm-M-x
	wdired-finish-edit
	))
